version: '3.3'
services:
  mysql:
    image: mysql:latest
    ports: 
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=admin1
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    expose:
      - 80
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql